BLACKLIST = [
    "[main/",
    "Could not determine spawn bucket of",
    "Maximum spawn attempts reached",
    "Herd members for",
    "An Alpha Pokemon has spawned",
    "Skipping Entity with id cobblemon_pokemon_entity_placeholder",
    "Entity PokemonEntity",
    "Display entityNot a string",
    "Named entity",
    "Registered trainer player",
    "Unregistered trainer player",
    "Sending server config values",
    "Receiving client config",
    "Registered the cobblemon:",
    "Registered the mega_showdown:",
    "Registered the cobblenav:",
    "Registering C2S receiver",
    "Start loading plugin from",
    "Registering Block Entities for",
    "Registering mod entities for",
    "Registering block entities for",
    "Started DhServerLevel",
    "Closed DHLevel",
    "Closed DhWorld",
    "Started [DhServerWorld]",
    "Set world gen queue",
    "Closing world gen queue",
    "Creating world gen queue",
    "Created world gen queue",
    "Closing WorldGenerationQueue",
    "Closing [BatchGenerationEnvironment]",
    "Finished closing WorldGenerationQueue",
    "BatchGenerator",
    "World generator thread pool",
    "No migration necessary",
    "C2ME detected",
    "Batch Chunk Generator",
    "Saving chunks for level",
    "ThreadedAnvilChunkStorage",
    "Saving players",
    "Saving worlds",
    "        __",
    "  |    |__)",
    "  |___ |",
    "[REI]",
    "---",
    "===",
    "OOOO",
    "~~~~",
    "[Discord]",
]

DEATH_MESSAGES = [
    "was slain by",
    "was shot by",
    "was killed by",
    "was pummeled by",
    "was fireballed by",
    "was stung by",
    "was impaled by",
    "was squashed by",
    "fell from a high place",
    "fell off a ladder",
    "fell off scaffolding",
    "fell off some vines",
    "fell off some twisting vines",
    "fell off some weeping vines",
    "fell while climbing",
    "hit the ground too hard",
    "was doomed to fall",
    "fell too far and was finished by",
    "was struck by lightning",
    "drowned",
    "suffocated in a wall",
    "was squished too much",
    "was blown up by",
    "was killed by [Intentional Game Design]",
    "went up in flames",
    "burned to death",
    "was burnt to a crisp",
    "went off with a bang",
    "tried to swim in lava",
    "discovered the floor was lava",
    "walked into fire",
    "was frozen to death",
    "froze to death",
    "starved to death",
    "was pricked to death",
    "walked into a cactus",
    "was poked to death by a sweet berry bush",
    "died from dehydration",
    "withered away",
    "was obliterated by a sonically-charged shriek",
    "experienced kinetic energy",
    "didn't want to live in the same world as",
    "was roasted in dragon's breath",
    "blew up",
    "was killed trying to hurt",
    "was stung to death",
]